name: torch
channels:
  - defaults
  - pytorch
dependencies:
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.8.2
  - pytorch=1.4.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
